name: Deployment
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: memo-wall
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_HOST: postgres
  POSTGRES_DB_TEST: memo-wall-test

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd BAD005/review
          yarn install 
          yarn knex migrate:latest --knexfile src/knexfile --env development
          yarn test
          yarn start
        env:
          DB_NAME: ${{env.POSTGRES_DB}}
          DB_USER: ${{env.POSTGRES_USER}}
          DB_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          DB_HOST: postgres
